name: Deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    concurrency: cd-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: src
